CONFIG_FILE_NAME: save.yml
batch_size: 8
debug: false
device: !!python/object/apply:torch.device
- cuda
dropout: 0.1
embedding_dim: 256
epochs: 200
event_dim: 388
experiment: embedding256-layer6
fp16: null
l_r: 0.1
label_smooth: 0.0
load_path: null
max_seq: 512
num_layers: 6
pad_token: 3
pickle_dir: ./Dataset/TrainingMIDI
positional: false
relative: false
token_eos: 390
token_sos: 389
vocab_size: 391
